In [1]:
import pandas as pd

df = pd.read_csv("1.csv")

In [2]:
df

    index             Order ID  Cust ID Gender  Age Age Group       Date Month
0       1  171-1029312-3038738  1029312  Women   44     Adult  12/4/2022   Dec
1       2  405-2183842-2225946  2183842  Women   29  Teenegar  12/4/2022   Dec
2       3  171-1641533-8921966  1641533  Women   67    Senior  12/4/2022   Dec
3       4  404-7490807-6300351  7490807  Women   20  Teenegar  12/4/2022   Dec
4       5  403-9293516-4577154  9293516  Women   62    Senior  12/4/2022   Dec
5       6  407-1298130-0368305  1298130    Men   49     Adult  12/4/2022   Dec
6       7  407-1298130-0368305  1298130  Women   23  Teenegar  12/4/2022   Dec
7       8  171-5561216-3398711  5561216  Women   70    Senior  12/4/2022   Dec
8       9  408-2935263-2935550  2935263  Women   75    Senior  12/4/2022   Dec
9      10  404-2648970-9042715  2648970  Women   43     Adult  12/4/2022   Dec
10     11  404-2648970-9042715  2648970  Women   76    Senior  12/4/2022   Dec
11     12  404-2648970-9042715  2648970  Women   45     Adult  12/4/2022   Dec
12     13  408-0265357-4939534   265357  Women   18  Teenegar  12/4/2022   Dec
13     14  403-9268874-7296313  9268874    Men   44     Adult  12/4/2022   Dec
14     15  407-0442660-2736366   442660  Women   52    Senior  12/4/2022   Dec
15     16  406-7482261-1657136  7482261  Women   18  Teenegar  12/4/2022   Dec
16     17  407-7039962-7080347  7039962    Men   30     Adult  12/4/2022   Dec
17     18  407-3422488-7373923  3422488  Women   48     Adult  12/4/2022   Dec
18     19  171-8974687-6745940  8974687    Men   24  Teenegar  12/4/2022   Dec
19     20  406-0244536-2177175   244536  Women   46     Adult  12/4/2022   Dec
20     21  404-4376789-3345166  4376789  Women   43     Adult  12/4/2022   Dec
21     22  408-1943310-9789160  1943310    Men   31     Adult  12/4/2022   Dec
22     23  403-0950590-5005155   950590    Men   30     Adult  12/4/2022   Dec
23     24  406-3935670-5720350  3935670  Women   19  Teenegar  12/4/2022   Dec
24     25  402-0398999-0011565   398999  Women   37     Adult  12/4/2022   Dec

In [3]:
import pandas as pd

df = pd.read_csv("1.csv")

In [4]:
df

,Customer Details,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,index,Order ID,Cust ID,Gender,Age,Age Group,Date,Month
1,1,171-1029312-3038738,1029312,Women,44,Adult,12/4/2022,Dec
2,2,405-2183842-2225946,2183842,Women,29,Teenegar,12/4/2022,Dec
3,3,171-1641533-8921966,1641533,Women,67,Senior,12/4/2022,Dec
4,4,404-7490807-6300351,7490807,Women,20,Teenegar,12/4/2022,Dec
5,5,403-9293516-4577154,9293516,Women,62,Senior,12/4/2022,Dec
6,6,407-1298130-0368305,1298130,Men,49,Adult,12/4/2022,Dec
7,7,407-1298130-0368305,1298130,Women,23,Teenegar,12/4/2022,Dec
8,8,171-5561216-3398711,5561216,Women,70,Senior,12/4/2022,Dec
9,9,408-2935263-2935550,2935263,Women,75,Senior,12/4/2022,Dec
10,10,404-2648970-9042715,2648970,Women,43,Adult,12/4/2022,Dec
11,11,404-2648970-9042715,2648970,Women,76,Senior,12/4/2022,Dec
12,12,404-2648970-9042715,2648970,Women,45,Adult,12/4/2022,Dec
13,13,408-0265357-4939534,265357,Women,18,Teenegar,12/4/2022,Dec
14,14,403-9268874-7296313,9268874,Men,44,Adult,12/4/2022,Dec
15,15,407-0442660-2736366,442660,Women,52,Senior,12/4/2022,Dec
16,16,406-7482261-1657136,7482261,Women,18,Teenegar,12/4/2022,Dec
17,17,407-7039962-7080347,7039962,Men,30,Adult,12/4/2022,Dec
18,18,407-3422488-7373923,3422488,Women,48,Adult,12/4/2022,Dec
19,19,171-8974687-6745940,8974687,Men,24,Teenegar,12/4/2022,Dec
20,20,406-0244536-2177175,244536,Women,46,Adult,12/4/2022,Dec
21,21,404-4376789-3345166,4376789,Women,43,Adult,12/4/2022,Dec
22,22,408-1943310-9789160,1943310,Men,31,Adult,12/4/2022,Dec
23,23,403-0950590-5005155,950590,Men,30,Adult,12/4/2022,Dec
24,24,406-3935670-5720350,3935670,Women,19,Teenegar,12/4/2022,Dec
25,25,402-0398999-0011565,398999,Women,37,Adult,12/4/2022,Dec

In [5]:
import pandas as pd

df = pd.read_csv("1.csv", skiprows=1)

df

    index             Order ID  Cust ID Gender  Age Age Group       Date Month
0       1  171-1029312-3038738  1029312  Women   44     Adult  12/4/2022   Dec
1       2  405-2183842-2225946  2183842  Women   29  Teenegar  12/4/2022   Dec
2       3  171-1641533-8921966  1641533  Women   67    Senior  12/4/2022   Dec
3       4  404-7490807-6300351  7490807  Women   20  Teenegar  12/4/2022   Dec
4       5  403-9293516-4577154  9293516  Women   62    Senior  12/4/2022   Dec
5       6  407-1298130-0368305  1298130    Men   49     Adult  12/4/2022   Dec
6       7  407-1298130-0368305  1298130  Women   23  Teenegar  12/4/2022   Dec
7       8  171-5561216-3398711  5561216  Women   70    Senior  12/4/2022   Dec
8       9  408-2935263-2935550  2935263  Women   75    Senior  12/4/2022   Dec
9      10  404-2648970-9042715  2648970  Women   43     Adult  12/4/2022   Dec
10     11  404-2648970-9042715  2648970  Women   76    Senior  12/4/2022   Dec
11     12  404-2648970-9042715  2648970  Women   45     Adult  12/4/2022   Dec
12     13  408-0265357-4939534   265357  Women   18  Teenegar  12/4/2022   Dec
13     14  403-9268874-7296313  9268874    Men   44     Adult  12/4/2022   Dec
14     15  407-0442660-2736366   442660  Women   52    Senior  12/4/2022   Dec
15     16  406-7482261-1657136  7482261  Women   18  Teenegar  12/4/2022   Dec
16     17  407-7039962-7080347  7039962    Men   30     Adult  12/4/2022   Dec
17     18  407-3422488-7373923  3422488  Women   48     Adult  12/4/2022   Dec
18     19  171-8974687-6745940  8974687    Men   24  Teenegar  12/4/2022   Dec
19     20  406-0244536-2177175   244536  Women   46     Adult  12/4/2022   Dec
20     21  404-4376789-3345166  4376789  Women   43     Adult  12/4/2022   Dec
21     22  408-1943310-9789160  1943310    Men   31     Adult  12/4/2022   Dec
22     23  403-0950590-5005155   950590    Men   30     Adult  12/4/2022   Dec
23     24  406-3935670-5720350  3935670  Women   19  Teenegar  12/4/2022   Dec
24     25  402-0398999-0011565   398999  Women   37     Adult  12/4/2022   Dec

In [6]:
import pandas as pd

df = pd.read_csv("1.csv", header=1)

df

    index             Order ID  Cust ID Gender  Age Age Group       Date Month
0       1  171-1029312-3038738  1029312  Women   44     Adult  12/4/2022   Dec
1       2  405-2183842-2225946  2183842  Women   29  Teenegar  12/4/2022   Dec
2       3  171-1641533-8921966  1641533  Women   67    Senior  12/4/2022   Dec
3       4  404-7490807-6300351  7490807  Women   20  Teenegar  12/4/2022   Dec
4       5  403-9293516-4577154  9293516  Women   62    Senior  12/4/2022   Dec
5       6  407-1298130-0368305  1298130    Men   49     Adult  12/4/2022   Dec
6       7  407-1298130-0368305  1298130  Women   23  Teenegar  12/4/2022   Dec
7       8  171-5561216-3398711  5561216  Women   70    Senior  12/4/2022   Dec
8       9  408-2935263-2935550  2935263  Women   75    Senior  12/4/2022   Dec
9      10  404-2648970-9042715  2648970  Women   43     Adult  12/4/2022   Dec
10     11  404-2648970-9042715  2648970  Women   76    Senior  12/4/2022   Dec
11     12  404-2648970-9042715  2648970  Women   45     Adult  12/4/2022   Dec
12     13  408-0265357-4939534   265357  Women   18  Teenegar  12/4/2022   Dec
13     14  403-9268874-7296313  9268874    Men   44     Adult  12/4/2022   Dec
14     15  407-0442660-2736366   442660  Women   52    Senior  12/4/2022   Dec
15     16  406-7482261-1657136  7482261  Women   18  Teenegar  12/4/2022   Dec
16     17  407-7039962-7080347  7039962    Men   30     Adult  12/4/2022   Dec
17     18  407-3422488-7373923  3422488  Women   48     Adult  12/4/2022   Dec
18     19  171-8974687-6745940  8974687    Men   24  Teenegar  12/4/2022   Dec
19     20  406-0244536-2177175   244536  Women   46     Adult  12/4/2022   Dec
20     21  404-4376789-3345166  4376789  Women   43     Adult  12/4/2022   Dec
21     22  408-1943310-9789160  1943310    Men   31     Adult  12/4/2022   Dec
22     23  403-0950590-5005155   950590    Men   30     Adult  12/4/2022   Dec
23     24  406-3935670-5720350  3935670  Women   19  Teenegar  12/4/2022   Dec
24     25  402-0398999-0011565   398999  Women   37     Adult  12/4/2022   Dec

In [9]:
import pandas as pd

df = pd.read_csv("2.csv", header=None)

df

     0                    1        2      3   4         5          6    7
0    1  171-1029312-3038738  1029312  Women  44     Adult  12/4/2022  Dec
1    2  405-2183842-2225946  2183842  Women  29  Teenegar  12/4/2022  Dec
2    3  171-1641533-8921966  1641533  Women  67    Senior  12/4/2022  Dec
3    4  404-7490807-6300351  7490807  Women  20  Teenegar  12/4/2022  Dec
4    5  403-9293516-4577154  9293516  Women  62    Senior  12/4/2022  Dec
5    6  407-1298130-0368305  1298130    Men  49     Adult  12/4/2022  Dec
6    7  407-1298130-0368305  1298130  Women  23  Teenegar  12/4/2022  Dec
7    8  171-5561216-3398711  5561216  Women  70    Senior  12/4/2022  Dec
8    9  408-2935263-2935550  2935263  Women  75    Senior  12/4/2022  Dec
9   10  404-2648970-9042715  2648970  Women  43     Adult  12/4/2022  Dec
10  11  404-2648970-9042715  2648970  Women  76    Senior  12/4/2022  Dec
11  12  404-2648970-9042715  2648970  Women  45     Adult  12/4/2022  Dec
12  13  408-0265357-4939534   265357  Women  18  Teenegar  12/4/2022  Dec
13  14  403-9268874-7296313  9268874    Men  44     Adult  12/4/2022  Dec
14  15  407-0442660-2736366   442660  Women  52    Senior  12/4/2022  Dec
15  16  406-7482261-1657136  7482261  Women  18  Teenegar  12/4/2022  Dec
16  17  407-7039962-7080347  7039962    Men  30     Adult  12/4/2022  Dec
17  18  407-3422488-7373923  3422488  Women  48     Adult  12/4/2022  Dec
18  19  171-8974687-6745940  8974687    Men  24  Teenegar  12/4/2022  Dec
19  20  406-0244536-2177175   244536  Women  46     Adult  12/4/2022  Dec
20  21  404-4376789-3345166  4376789  Women  43     Adult  12/4/2022  Dec
21  22  408-1943310-9789160  1943310    Men  31     Adult  12/4/2022  Dec
22  23  403-0950590-5005155   950590    Men  30     Adult  12/4/2022  Dec
23  24  406-3935670-5720350  3935670  Women  19  Teenegar  12/4/2022  Dec
24  25  402-0398999-0011565   398999  Women  37     Adult  12/4/2022  Dec

In [10]:
import pandas as pd

df = pd.read_csv("2.csv", header=None, names=['index','order id','customer id','gender','age','age group','date','month'])

df

,index,order id,customer id,gender,age,age group,date,month
0,1,171-1029312-3038738,1029312,Women,44,Adult,12/4/2022,Dec
1,2,405-2183842-2225946,2183842,Women,29,Teenegar,12/4/2022,Dec
2,3,171-1641533-8921966,1641533,Women,67,Senior,12/4/2022,Dec
3,4,404-7490807-6300351,7490807,Women,20,Teenegar,12/4/2022,Dec
4,5,403-9293516-4577154,9293516,Women,62,Senior,12/4/2022,Dec
5,6,407-1298130-0368305,1298130,Men,49,Adult,12/4/2022,Dec
6,7,407-1298130-0368305,1298130,Women,23,Teenegar,12/4/2022,Dec
7,8,171-5561216-3398711,5561216,Women,70,Senior,12/4/2022,Dec
8,9,408-2935263-2935550,2935263,Women,75,Senior,12/4/2022,Dec
9,10,404-2648970-9042715,2648970,Women,43,Adult,12/4/2022,Dec
10,11,404-2648970-9042715,2648970,Women,76,Senior,12/4/2022,Dec
11,12,404-2648970-9042715,2648970,Women,45,Adult,12/4/2022,Dec
12,13,408-0265357-4939534,265357,Women,18,Teenegar,12/4/2022,Dec
13,14,403-9268874-7296313,9268874,Men,44,Adult,12/4/2022,Dec
14,15,407-0442660-2736366,442660,Women,52,Senior,12/4/2022,Dec
15,16,406-7482261-1657136,7482261,Women,18,Teenegar,12/4/2022,Dec
16,17,407-7039962-7080347,7039962,Men,30,Adult,12/4/2022,Dec
17,18,407-3422488-7373923,3422488,Women,48,Adult,12/4/2022,Dec
18,19,171-8974687-6745940,8974687,Men,24,Teenegar,12/4/2022,Dec
19,20,406-0244536-2177175,244536,Women,46,Adult,12/4/2022,Dec
20,21,404-4376789-3345166,4376789,Women,43,Adult,12/4/2022,Dec
21,22,408-1943310-9789160,1943310,Men,31,Adult,12/4/2022,Dec
22,23,403-0950590-5005155,950590,Men,30,Adult,12/4/2022,Dec
23,24,406-3935670-5720350,3935670,Women,19,Teenegar,12/4/2022,Dec
24,25,402-0398999-0011565,398999,Women,37,Adult,12/4/2022,Dec

In [12]:
import pandas as pd

df = pd.read_csv("3.csv", nrows=3)

df

   index             Order ID  Cust ID Gender  Age Age Group       Date Month
0      1  171-1029312-3038738  1029312  Women   44     Adult  12/4/2022   Dec
1      2  405-2183842-2225946  2183842  Women   29  Teenegar  12/4/2022   Dec
2      3  171-1641533-8921966  1641533  Women   67    Senior  12/4/2022   Dec

In [14]:
import pandas as pd

df = pd.read_csv("3.csv", na_values=[46,37])

df

,index,Order ID,Cust ID,Gender,Age,Age Group,Date,Month
0,1,171-1029312-3038738,1029312,Women,44.0,Adult,12/4/2022,Dec
1,2,405-2183842-2225946,2183842,Women,29.0,Teenegar,12/4/2022,Dec
2,3,171-1641533-8921966,1641533,Women,67.0,Senior,12/4/2022,Dec
3,4,404-7490807-6300351,7490807,Women,20.0,Teenegar,12/4/2022,Dec
4,5,403-9293516-4577154,9293516,Women,62.0,Senior,12/4/2022,Dec
5,6,407-1298130-0368305,1298130,Men,49.0,Adult,12/4/2022,Dec
6,7,407-1298130-0368305,1298130,Women,23.0,Teenegar,12/4/2022,Dec
7,8,171-5561216-3398711,5561216,Women,70.0,Senior,12/4/2022,Dec
8,9,408-2935263-2935550,2935263,Women,75.0,Senior,12/4/2022,Dec
9,10,404-2648970-9042715,2648970,Women,43.0,Adult,12/4/2022,Dec
10,11,404-2648970-9042715,2648970,Women,76.0,Senior,12/4/2022,Dec
11,12,404-2648970-9042715,2648970,Women,45.0,Adult,12/4/2022,Dec
12,13,408-0265357-4939534,265357,Women,18.0,Teenegar,12/4/2022,Dec
13,14,403-9268874-7296313,9268874,Men,44.0,Adult,12/4/2022,Dec
14,15,407-0442660-2736366,442660,Women,52.0,Senior,12/4/2022,Dec
15,16,406-7482261-1657136,7482261,Women,18.0,Teenegar,12/4/2022,Dec
16,17,407-7039962-7080347,7039962,Men,30.0,Adult,12/4/2022,Dec
17,18,407-3422488-7373923,3422488,Women,48.0,Adult,12/4/2022,Dec
18,19,171-8974687-6745940,8974687,Men,24.0,Teenegar,12/4/2022,Dec
19,20,406-0244536-2177175,244536,Women,NaN,Adult,12/4/2022,Dec
20,21,404-4376789-3345166,4376789,Women,43.0,Adult,12/4/2022,Dec
21,22,408-1943310-9789160,1943310,Men,31.0,Adult,12/4/2022,Dec
22,23,403-0950590-5005155,950590,Men,30.0,Adult,12/4/2022,Dec
23,24,406-3935670-5720350,3935670,Women,19.0,Teenegar,12/4/2022,Dec
24,25,402-0398999-0011565,398999,Women,NaN,Adult,12/4/2022,Dec

In [19]:
import pandas as pd

df = pd.read_csv("3.csv", na_values={
    'Age': [44,20],
    'Age Group': ['Adult','Senior']
})

df

,index,Order ID,Cust ID,Gender,Age,Age Group,Date,Month
0,1,171-1029312-3038738,1029312,Women,NaN,NaN,12/4/2022,Dec
1,2,405-2183842-2225946,2183842,Women,29.0,Teenegar,12/4/2022,Dec
2,3,171-1641533-8921966,1641533,Women,67.0,NaN,12/4/2022,Dec
3,4,404-7490807-6300351,7490807,Women,NaN,Teenegar,12/4/2022,Dec
4,5,403-9293516-4577154,9293516,Women,62.0,NaN,12/4/2022,Dec
5,6,407-1298130-0368305,1298130,Men,49.0,NaN,12/4/2022,Dec
6,7,407-1298130-0368305,1298130,Women,23.0,Teenegar,12/4/2022,Dec
7,8,171-5561216-3398711,5561216,Women,70.0,NaN,12/4/2022,Dec
8,9,408-2935263-2935550,2935263,Women,75.0,NaN,12/4/2022,Dec
9,10,404-2648970-9042715,2648970,Women,43.0,NaN,12/4/2022,Dec
10,11,404-2648970-9042715,2648970,Women,76.0,NaN,12/4/2022,Dec
11,12,404-2648970-9042715,2648970,Women,45.0,NaN,12/4/2022,Dec
12,13,408-0265357-4939534,265357,Women,18.0,Teenegar,12/4/2022,Dec
13,14,403-9268874-7296313,9268874,Men,NaN,NaN,12/4/2022,Dec
14,15,407-0442660-2736366,442660,Women,52.0,NaN,12/4/2022,Dec
15,16,406-7482261-1657136,7482261,Women,18.0,Teenegar,12/4/2022,Dec
16,17,407-7039962-7080347,7039962,Men,30.0,NaN,12/4/2022,Dec
17,18,407-3422488-7373923,3422488,Women,48.0,NaN,12/4/2022,Dec
18,19,171-8974687-6745940,8974687,Men,24.0,Teenegar,12/4/2022,Dec
19,20,406-0244536-2177175,244536,Women,46.0,NaN,12/4/2022,Dec
20,21,404-4376789-3345166,4376789,Women,43.0,NaN,12/4/2022,Dec
21,22,408-1943310-9789160,1943310,Men,31.0,NaN,12/4/2022,Dec
22,23,403-0950590-5005155,950590,Men,30.0,NaN,12/4/2022,Dec
23,24,406-3935670-5720350,3935670,Women,19.0,Teenegar,12/4/2022,Dec
24,25,402-0398999-0011565,398999,Women,37.0,NaN,12/4/2022,Dec

<h1>Write csv</h1>

In [21]:
df.to_csv('new2.csv')

In [22]:
df.to_csv('new2.csv', index=False)

In [23]:
df.columns

Index(['index', 'Order ID', 'Cust ID', 'Gender', 'Age', 'Age Group', 'Date',
       'Month'],
      dtype='object')

In [24]:
df.to_csv('new2.csv', columns=['index','Order ID'])

In [26]:
df.to_csv('new2.csv', header=False)

In [1]:
import pandas as pd
import openpyxl

In [4]:
df = pd.read_excel("4.xlsx",sheet_name="3")

In [5]:
df

    index             Order ID  Cust ID Gender  Age Age Group       Date Month
0       1  171-1029312-3038738  1029312  Women   44     Adult 2022-12-04   Dec
1       2  405-2183842-2225946  2183842  Women   29  Teenegar 2022-12-04   Dec
2       3  171-1641533-8921966  1641533  Women   67    Senior 2022-12-04   Dec
3       4  404-7490807-6300351  7490807  Women   20  Teenegar 2022-12-04   Dec
4       5  403-9293516-4577154  9293516  Women   62    Senior 2022-12-04   Dec
5       6  407-1298130-0368305  1298130    Men   49     Adult 2022-12-04   Dec
6       7  407-1298130-0368305  1298130  Women   23  Teenegar 2022-12-04   Dec
7       8  171-5561216-3398711  5561216  Women   70    Senior 2022-12-04   Dec
8       9  408-2935263-2935550  2935263  Women   75    Senior 2022-12-04   Dec
9      10  404-2648970-9042715  2648970  Women   43     Adult 2022-12-04   Dec
10     11  404-2648970-9042715  2648970  Women   76    Senior 2022-12-04   Dec
11     12  404-2648970-9042715  2648970  Women   45     Adult 2022-12-04   Dec
12     13  408-0265357-4939534   265357  Women   18  Teenegar 2022-12-04   Dec
13     14  403-9268874-7296313  9268874    Men   44     Adult 2022-12-04   Dec
14     15  407-0442660-2736366   442660  Women   52    Senior 2022-12-04   Dec
15     16  406-7482261-1657136  7482261  Women   18  Teenegar 2022-12-04   Dec
16     17  407-7039962-7080347  7039962    Men   30     Adult 2022-12-04   Dec
17     18  407-3422488-7373923  3422488  Women   48     Adult 2022-12-04   Dec
18     19  171-8974687-6745940  8974687    Men   24  Teenegar 2022-12-04   Dec
19     20  406-0244536-2177175   244536  Women   46     Adult 2022-12-04   Dec
20     21  404-4376789-3345166  4376789  Women   43     Adult 2022-12-04   Dec
21     22  408-1943310-9789160  1943310    Men   31     Adult 2022-12-04   Dec
22     23  403-0950590-5005155   950590    Men   30     Adult 2022-12-04   Dec
23     24  406-3935670-5720350  3935670  Women   19  Teenegar 2022-12-04   Dec
24     25  402-0398999-0011565   398999  Women   37     Adult 2022-12-04   Dec

In [7]:
import pandas as pd
import openpyxl

def convert_people_cell(cell):
    if cell==44:
        return 'NAN'
    return cell
df = pd.read_excel("4.xlsx",sheet_name="3", converters = {
    'Age': convert_people_cell
})

df

    index             Order ID  Cust ID Gender  Age Age Group       Date Month
0       1  171-1029312-3038738  1029312  Women  NAN     Adult 2022-12-04   Dec
1       2  405-2183842-2225946  2183842  Women   29  Teenegar 2022-12-04   Dec
2       3  171-1641533-8921966  1641533  Women   67    Senior 2022-12-04   Dec
3       4  404-7490807-6300351  7490807  Women   20  Teenegar 2022-12-04   Dec
4       5  403-9293516-4577154  9293516  Women   62    Senior 2022-12-04   Dec
5       6  407-1298130-0368305  1298130    Men   49     Adult 2022-12-04   Dec
6       7  407-1298130-0368305  1298130  Women   23  Teenegar 2022-12-04   Dec
7       8  171-5561216-3398711  5561216  Women   70    Senior 2022-12-04   Dec
8       9  408-2935263-2935550  2935263  Women   75    Senior 2022-12-04   Dec
9      10  404-2648970-9042715  2648970  Women   43     Adult 2022-12-04   Dec
10     11  404-2648970-9042715  2648970  Women   76    Senior 2022-12-04   Dec
11     12  404-2648970-9042715  2648970  Women   45     Adult 2022-12-04   Dec
12     13  408-0265357-4939534   265357  Women   18  Teenegar 2022-12-04   Dec
13     14  403-9268874-7296313  9268874    Men  NAN     Adult 2022-12-04   Dec
14     15  407-0442660-2736366   442660  Women   52    Senior 2022-12-04   Dec
15     16  406-7482261-1657136  7482261  Women   18  Teenegar 2022-12-04   Dec
16     17  407-7039962-7080347  7039962    Men   30     Adult 2022-12-04   Dec
17     18  407-3422488-7373923  3422488  Women   48     Adult 2022-12-04   Dec
18     19  171-8974687-6745940  8974687    Men   24  Teenegar 2022-12-04   Dec
19     20  406-0244536-2177175   244536  Women   46     Adult 2022-12-04   Dec
20     21  404-4376789-3345166  4376789  Women   43     Adult 2022-12-04   Dec
21     22  408-1943310-9789160  1943310    Men   31     Adult 2022-12-04   Dec
22     23  403-0950590-5005155   950590    Men   30     Adult 2022-12-04   Dec
23     24  406-3935670-5720350  3935670  Women   19  Teenegar 2022-12-04   Dec
24     25  402-0398999-0011565   398999  Women   37     Adult 2022-12-04   Dec

In [9]:
df.to_excel('new10.xlsx', sheet_name='new110')

In [13]:
df.to_excel('new10.xlsx', sheet_name='new110',startrow=2, startcol=2, index=False)

In [14]:
df_stocks = pd.DataFrame({
    'ticket': ['Google','WMT'],
    'price': [44,37],
})

df_weather = pd.DataFrame({
    'day': ['1/1/2024'],
    'tem': [32]
})

In [15]:
with pd.ExcelWriter('stock_price.xlsx') as writer:
    df_stocks.to_excel(writer, sheet_name = "stocks")
    df_weather.to_excel(writer, sheet_name = "weather")